services:
  pandoc-mermaid-crossref:
    platform: linux/amd64
    build:
      context: .
    image: mattstomper/puppeteer-pandoc-mermaid-crossref:1.1.0-rc1
    entrypoint: ./svd.sh
    working_dir: /home/node/data/svd_example
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ./svd_example:/home/node/data/svd_example
